name: Compile snapshot with Maven
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11.0.12
        uses: actions/setup-java@v2
        with:
          java-version: '11.0.12'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean install
      - name: Get artifactId and version
        run: |
          ARTIFACT_ID=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.artifactId}' --non-recursive exec:exec)
          VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
          echo "ARTIFACT_ID=$ARTIFACT_ID" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Publish JAR
        run: |
          COMMIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
          mv ${{ github.workspace }}/target/$ARTIFACT_ID-$VERSION.jar ${{ github.workspace }}/target/$ARTIFACT_ID-$VERSION-$COMMIT_HASH.jar
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}
          path: ${{ github.workspace }}/target/${{ env.ARTIFACT_ID }}-${{ env.VERSION }}-${{ env.COMMIT_HASH }}.jar